backend:
  name: github
  repo: mimecine/kbook-astro
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/img"
public_folder: "img"


collections:
  - name: products
    identifier_field: handle